// Ported from 'Yallo App.dc.html'.
import { buildStrings } from './i18n.js';

export function buildData() {
  const stores = [
    [
      's1',
      'Dar Zitoun',
      'Moroccan · Tajine · Couscous',
      'restaurants',
      4.8,
      '1.2k',
      1200,
      25,
      35,
      9,
      2,
      60,
      'Médina',
      false,
      'cover · tajine',
      'DZ',
    ],
    [
      's2',
      'Burger Atlas',
      'Burgers · American',
      'restaurants',
      4.6,
      '860',
      860,
      15,
      25,
      0,
      2,
      50,
      'Guéliz',
      false,
      'cover · smash burger',
      'BA',
    ],
    [
      's3',
      'Pizzeria Guéliz',
      'Pizza · Italian',
      'restaurants',
      4.5,
      '640',
      640,
      30,
      40,
      12,
      2,
      60,
      'Guéliz',
      false,
      'cover · wood oven',
      'PG',
    ],
    [
      's4',
      'Pâtisserie Al Warda',
      'Moroccan pastries · Breakfast',
      'bakery',
      4.9,
      '2.1k',
      2100,
      15,
      20,
      7,
      1,
      30,
      'Guéliz',
      false,
      'cover · cornes de gazelle',
      'AW',
    ],
    [
      's5',
      'Souk Frais Market',
      'Groceries · Fresh produce',
      'groceries',
      4.7,
      '1.5k',
      1500,
      20,
      30,
      10,
      1,
      50,
      'Hivernage',
      false,
      'cover · market stall',
      'SF',
    ],
    [
      's6',
      'Pharmacie Ibn Sina',
      'Pharmacy · Parapharmacy',
      'pharmacy',
      4.8,
      '930',
      930,
      20,
      30,
      10,
      2,
      0,
      'Guéliz',
      false,
      'cover · pharmacy shelf',
      'IS',
    ],
    [
      's7',
      'Jus Jemaa',
      'Fresh juices · Coffee',
      'drinks',
      4.6,
      '410',
      410,
      10,
      20,
      5,
      1,
      20,
      'Jemaa el-Fna',
      false,
      'cover · orange stand',
      'JJ',
    ],
    [
      's8',
      'Maison Argane',
      'Hammam · Beauty · Crafts',
      'shops',
      4.7,
      '280',
      280,
      35,
      50,
      15,
      3,
      50,
      'Médina',
      false,
      'cover · argan jars',
      'MA',
    ],
    ['s9', 'Sushi Majorelle', 'Sushi · Asian', 'restaurants', 4.4, '350', 350, 30, 45, 15, 3, 80, 'Majorelle', true, 'cover · maki', 'SM'],
    [
      's10',
      'Snack Chez Hamid',
      'Street food · Sandwiches',
      'restaurants',
      4.5,
      '1.8k',
      1800,
      15,
      25,
      6,
      1,
      30,
      'Bab Doukkala',
      false,
      'cover · grill',
      'CH',
    ],
  ].map((a) => ({
    id: a[0],
    name: a[1],
    cuisine: a[2],
    cat: a[3],
    rating: a[4],
    reviews: a[5],
    rc: a[6],
    tMin: a[7],
    tMax: a[8],
    fee: a[9],
    price: a[10],
    min: a[11],
    area: a[12],
    closed: a[13],
    img: a[14],
    initials: a[15],
    opens: '19:00',
  }));
  const products = [
    [
      'p1-1',
      's1',
      'Tajines',
      'Chicken tajine, preserved lemon & olives',
      'Slow-cooked in clay with saffron, ginger and Meslalla olives.',
      85,
      'tajine',
      'tajine',
      1,
    ],
    [
      'p1-2',
      's1',
      'Tajines',
      'Lamb tajine with prunes & almonds',
      'Tender lamb shoulder, caramelised prunes, toasted almonds and sesame.',
      110,
      'tajine',
      'tajine',
      1,
    ],
    [
      'p1-3',
      's1',
      'Tajines',
      'Kefta tajine with eggs',
      'Spiced beef meatballs in tomato sauce, finished with eggs.',
      70,
      'tajine',
      'tajine',
      0,
    ],
    [
      'p1-4',
      's1',
      'Couscous',
      'Couscous with seven vegetables',
      'Hand-rolled semolina, beef, chickpeas and seasonal vegetables.',
      90,
      'couscous',
      'tajine',
      1,
    ],
    ['p1-5', 's1', 'Couscous', 'Couscous tfaya', 'Chicken, caramelised onions, raisins and cinnamon.', 95, 'couscous', 'tajine', 0],
    ['p1-6', 's1', 'Starters', 'Chicken pastilla', 'Flaky warqa pastry, almonds, cinnamon and icing sugar.', 75, 'pastilla', null, 0],
    ['p1-7', 's1', 'Starters', 'Harira', 'Tomato, lentil and chickpea soup, served with dates.', 25, 'harira', null, 0],
    ['p1-8', 's1', 'Drinks', 'Mint tea · pot for two', 'Gunpowder green tea with fresh mint.', 20, 'atay', null, 0],
    ['p2-1', 's2', 'Burgers', 'Atlas smash burger', 'Two smashed beef patties, cheddar, pickles, house sauce.', 65, 'burger', 'burger', 1],
    ['p2-2', 's2', 'Burgers', 'Double harissa cheese', 'Beef, double cheddar, harissa mayo, grilled onions.', 85, 'burger', 'burger', 0],
    ['p2-3', 's2', 'Burgers', 'Crispy chicken', 'Buttermilk fried chicken, slaw, chipotle mayo.', 60, 'burger', 'burger', 0],
    ['p2-4', 's2', 'Sides', 'Loaded fries', 'Fries, cheese sauce, smoked beef, chives.', 30, 'fries', null, 0],
    ['p2-5', 's2', 'Drinks', 'Date & vanilla milkshake', 'Medjool dates, vanilla ice cream, milk.', 35, 'milkshake', null, 0],
    ['p3-1', 's3', 'Pizza', 'Margherita', 'San Marzano tomato, fior di latte, basil.', 60, 'pizza', 'pizza', 1],
    ['p3-2', 's3', 'Pizza', 'Kefta & merguez', 'Spiced kefta, merguez, peppers, mozzarella.', 80, 'pizza', 'pizza', 1],
    ['p3-3', 's3', 'Pizza', 'Quattro formaggi', 'Mozzarella, gorgonzola, parmesan, Chefchaouen goat cheese.', 85, 'pizza', 'pizza', 0],
    ['p3-4', 's3', 'Desserts', 'Tiramisu', 'Mascarpone, espresso, cocoa.', 35, 'tiramisu', null, 0],
    [
      'p4-1',
      's4',
      'Moroccan pastries',
      'Cornes de gazelle · 250 g',
      'Almond paste and orange blossom in a thin crescent.',
      60,
      'kaab el ghzal',
      null,
      1,
    ],
    ['p4-2', 's4', 'Moroccan pastries', 'Chebakia · 500 g', 'Sesame flowers, fried and dipped in honey.', 55, 'chebakia', null, 0],
    ['p4-3', 's4', 'Breakfast', 'Msemen · 4 pcs', 'Flaky square pancakes, made from 7 am.', 16, 'msemen', null, 1],
    ['p4-4', 's4', 'Breakfast', 'Croissant pur beurre', 'Baked every morning.', 7, 'croissant', null, 0],
    ['p4-5', 's4', 'Breakfast', 'Baghrir with honey & butter · 3 pcs', 'Thousand-hole semolina pancakes.', 18, 'baghrir', null, 0],
    ['p5-1', 's5', 'Fresh', 'Fresh mint · bunch', 'For tea — picked this morning.', 5, 'naanaa', null, 1],
    ['p5-2', 's5', 'Fresh', 'Oranges · 1 kg', 'Juicing oranges from Berkane.', 8, 'oranges', null, 0],
    ['p5-3', 's5', 'Fresh', 'Khobz · round loaf', 'Traditional wheat bread.', 3, 'khobz', null, 0],
    ['p5-4', 's5', 'Dairy & eggs', 'Beldi eggs · 12', 'Free-range country eggs.', 24, 'eggs', null, 0],
    ['p5-5', 's5', 'Dairy & eggs', 'Fresh milk · 1 L', 'Pasteurised whole milk.', 8.5, 'milk', null, 0],
    ['p5-6', 's5', 'Pantry', 'Olive oil from Meknès · 1 L', 'Extra virgin, first cold press.', 75, 'olive oil', null, 0],
    [
      'p5-7',
      's5',
      'Pantry',
      'Culinary argan oil · 250 ml',
      'Toasted, from a women’s cooperative near Essaouira.',
      120,
      'argan oil',
      null,
      1,
    ],
    [
      'p6-1',
      's6',
      'Pain & fever',
      'Paracetamol 1000 mg · 8 tablets',
      'Pain and fever relief. Read the leaflet.',
      19.6,
      'paracetamol',
      null,
      1,
    ],
    ['p6-2', 's6', 'Vitamins', 'Vitamin C 1000 mg · 20 effervescent', 'Orange flavour.', 45, 'vitamin c', null, 0],
    ['p6-3', 's6', 'Skin', 'Sunscreen SPF 50+ · 50 ml', 'Very high protection, fragrance-free.', 145, 'spf 50', null, 0],
    ['p6-4', 's6', 'Baby', 'Baby wipes · 72', 'Sensitive skin, alcohol-free.', 29, 'wipes', null, 0],
    ['p6-5', 's6', 'Devices', 'Digital thermometer', 'Reads in 10 seconds.', 89, 'thermometer', null, 0],
    ['p7-1', 's7', 'Juices', 'Fresh orange juice · 50 cl', 'Squeezed to order.', 15, 'orange juice', 'drink', 1],
    ['p7-2', 's7', 'Juices', 'Avocado & almond smoothie', 'Avocado, milk, almonds, a touch of dates.', 25, 'jus d’avocat', 'drink', 1],
    ['p7-3', 's7', 'Juices', 'Panaché', 'Banana, apple, orange and milk.', 22, 'panaché', 'drink', 0],
    ['p7-4', 's7', 'Coffee', 'Nous-nous', 'Half coffee, half milk, in a glass.', 12, 'nous-nous', null, 0],
    ['p8-1', 's8', 'Hammam', 'Savon beldi · black soap', 'Olive-based black soap with eucalyptus.', 35, 'savon beldi', null, 1],
    ['p8-2', 's8', 'Hammam', 'Rhassoul clay · 200 g', 'Atlas mountain clay for hair and skin.', 40, 'rhassoul', null, 0],
    ['p8-3', 's8', 'Beauty', 'Rose water from Kelâat M’Gouna', 'Distilled Damask roses, 250 ml.', 45, 'rose water', null, 0],
    ['p8-4', 's8', 'Home', 'Tea glasses · set of 6', 'Hand-painted, gold rim.', 90, 'tea glasses', null, 0],
    ['p9-1', 's9', 'Rolls', 'Salmon avocado roll · 8 pcs', 'Salmon, avocado, sesame.', 75, 'maki', null, 0],
    ['p9-2', 's9', 'Rolls', 'Crispy shrimp roll · 8 pcs', 'Tempura shrimp, spicy mayo.', 85, 'maki', null, 0],
    ['p10-1', 's10', 'Sandwiches', 'Kefta bocadillo', 'Grilled kefta, onions and harissa in fresh khobz.', 30, 'bocadillo', null, 1],
    ['p10-2', 's10', 'Sandwiches', 'Tacos mixte', 'Chicken, kefta, cheese sauce and fries in a grilled wrap.', 45, 'tacos', null, 1],
    ['p10-3', 's10', 'Breakfast', 'Msemen with cheese & honey', 'Folded msemen, soft cheese, honey.', 15, 'msemen', null, 0],
    ['p10-4', 's10', 'Breakfast', 'Sfenj · 3 pcs', 'Moroccan doughnuts, dusted with sugar.', 9, 'sfenj', null, 0],
  ].map((a) => ({ id: a[0], storeId: a[1], sec: a[2], name: a[3], desc: a[4], price: a[5], img: a[6], opt: a[7], pop: !!a[8] }));
  const OPT = {
    tajine: [
      {
        id: 'size',
        name: 'Portion',
        req: true,
        choices: [
          ['For 1', 0],
          ['For 2 to share', 70],
        ],
      },
      {
        id: 'side',
        name: 'Extras',
        multi: true,
        choices: [
          ['Extra khobz', 5],
          ['Olives & preserved lemon', 8],
          ['Mint tea pot', 20],
        ],
      },
    ],
    burger: [
      {
        id: 'side',
        name: 'Side',
        req: true,
        choices: [
          ['Fries', 0],
          ['Green salad', 0],
          ['Onion rings', 10],
        ],
      },
      {
        id: 'x',
        name: 'Add-ons',
        multi: true,
        choices: [
          ['Extra cheddar', 8],
          ['Fried egg', 6],
          ['Smoked beef', 12],
        ],
      },
    ],
    pizza: [
      {
        id: 'size',
        name: 'Size',
        req: true,
        choices: [
          ['Medium · 30 cm', 0],
          ['Large · 40 cm', 30],
        ],
      },
      {
        id: 'x',
        name: 'Extra toppings',
        multi: true,
        choices: [
          ['Olives', 6],
          ['Mushrooms', 8],
          ['Extra mozzarella', 12],
        ],
      },
    ],
    drink: [
      {
        id: 'size',
        name: 'Size',
        req: true,
        choices: [
          ['50 cl', 0],
          ['1 L', 12],
        ],
      },
      {
        id: 'sugar',
        name: 'Sugar',
        req: true,
        choices: [
          ['Normal', 0],
          ['A little', 0],
          ['No sugar', 0],
        ],
      },
    ],
  };
  const storeMap = {};
  stores.forEach((s) => (storeMap[s.id] = s));
  const prodMap = {};
  products.forEach((p) => (prodMap[p.id] = p));
  const addresses = [
    {
      id: 'a1',
      label: 'Home',
      city: 'Marrakech',
      district: 'Guéliz',
      street: '12 Rue de la Liberté',
      building: 'Imm. Nour, 3rd floor, Apt 7',
      landmark: 'Above Café Les Négociants',
    },
    {
      id: 'a2',
      label: 'Work',
      city: 'Marrakech',
      district: 'Hivernage',
      street: 'Avenue Mohammed VI',
      building: 'Bureau 204',
      landmark: 'Opposite Menara Mall',
    },
    {
      id: 'a3',
      label: 'Family',
      city: 'Casablanca',
      district: 'Maârif',
      street: '45 Rue Ibnou Mounir',
      building: 'Villa 3',
      landmark: 'Behind Twin Center',
    },
  ];
  const pastOrders = [
    {
      id: 'ZQ-47912',
      storeId: 's1',
      date: 'Sep 24 · 20:14',
      lines: [
        { pid: 'p1-1', qty: 1, unit: 85, sel: { size: [0], side: [] } },
        { pid: 'p1-8', qty: 1, unit: 20, sel: {} },
      ],
    },
    {
      id: 'ZQ-47650',
      storeId: 's6',
      date: 'Sep 21 · 11:02',
      lines: [
        { pid: 'p6-1', qty: 2, unit: 19.6, sel: {} },
        { pid: 'p6-2', qty: 1, unit: 45, sel: {} },
      ],
    },
    {
      id: 'ZQ-47288',
      storeId: 's4',
      date: 'Sep 18 · 08:30',
      lines: [
        { pid: 'p4-3', qty: 2, unit: 16, sel: {} },
        { pid: 'p4-4', qty: 4, unit: 7, sel: {} },
      ],
    },
  ].map((o) => {
    const sub = o.lines.reduce((a, l) => a + l.unit * l.qty, 0);
    const fee = storeMap[o.storeId].fee;
    return { ...o, sub, fee, service: 3, disc: 0, total: sub + fee + 3, status: 'delivered', addrId: 'a1', pay: 'cash' };
  });
  return {
    stores,
    storeMap,
    products,
    prodMap,
    OPT,
    addresses,
    pastOrders,
    T: buildStrings(),
    cats: ['restaurants', 'groceries', 'pharmacy', 'shops', 'bakery', 'drinks'],
  };
}
